SELECT *
FROM [HotelBooking ]..hotel_bookings;


--Top Booking Channel
SELECT distribution_channel, COUNT(*) AS total_bookings
FROM [HotelBooking ]..hotel_bookings
GROUP BY distribution_channel
ORDER BY total_bookings DESC;


-- Rate at which guests cancel
SELECT customer_type, COUNT (*) AS total_bookings, SUM(is_canceled) AS total_canceled, SUM(is_canceled) /  COUNT(*) AS cancellation_rate
FROM [HotelBooking ]..hotel_bookings
GROUP BY customer_type;


--Avg stay on wait list
SELECT market_segment, AVG(days_in_waiting_list) AS avg_length_of_stay
FROM [HotelBooking ]..hotel_bookings
GROUP BY market_segment
ORDER BY avg_length_of_stay;


--Number of adults from bookings
SELECT customer_type, SUM(adults) AS total_adults
FROM [HotelBooking ]..hotel_bookings
GROUP BY customer_type;


--Bookings by agent and associated country
SELECT country, hotel, agent, COUNT(*) AS num_bookings
FROM [HotelBooking ]..hotel_bookings
GROUP BY agent, country, hotel
ORDER BY num_bookings, country;


--Hotel Revenue growth/trend over time
SELECT arrival_date_year, round(SUM((adults + children)*adr), 2) AS total_revenue
FROM [HotelBooking ]..hotel_bookings
GROUP BY arrival_date_year;


--Segment revenue by hotel_type
SELECT hotel, market_segment, round(SUM((adults + children)*adr), 2) AS segment_revenue
FROM [HotelBooking ]..hotel_bookings
GROUP BY hotel, market_segment
ORDER BY hotel;


-- Trend in Guest with Cars
SELECT arrival_date_year, COUNT(*) AS total_bookings, SUM(required_car_parking_spaces) AS total_parking_space
FROM [HotelBooking ]..hotel_bookings
WHERE  required_car_parking_spaces > 0
GROUP BY arrival_date_year;


-- Calculating average daily rate and guest explore seasonability
SELECT arrival_date_month, AVG(adr) AS avg_adr, SUM(stays_in_weekend_nights) AS total_weekend_nights
FROM [HotelBooking ]..hotel_bookings
GROUP BY arrival_date_month
ORDER BY total_weekend_nights; 


-- Total revenue generated by hotel types
WITH Revenue_By_Hotel AS (
    SELECT 
        hotel, SUM(adr * (adults + children)) AS total_revenue
    FROM [HotelBooking ]..hotel_bookings
    GROUP BY hotel
)
SELECT hotel,total_revenue
FROM Revenue_By_Hotel
ORDER BY total_revenue DESC;
